config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root 'hello#world'

  # global file crud (active_storage)
  resources :files, only: %i[show create destroy]

  constraints format: :json do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
    }

    draw :api_routes
    draw :partner_center_routes
    draw :store_routes

    draw :common_routes
    draw :sellers_routes

    draw :external_channel_routes
  end

  namespace :haravan do
    namespace :settlement do
      resources :brands, only: %i[index show]
    end
  end

  devise_for :pandals
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/brand.rb
class Brand < NationRecord
  resourcify
  include Translatable
  include Approvable
  extend_has_one_attached :logo
  extend_has_one_attached :first_image
  translate_column :name

  belongs_to :company
  has_many :products
  has_many :product_item_groups
  has_many :items, through: :product_item_groups, class_name: 'ProductItem'
  has_many :managers, through: :company

  # ===============================================
  has_many :product_option_brands, class_name: 'ProductOptionBrand', dependent: :delete_all
  has_many :product_options, through: :product_option_brands
  # ===============================================
  has_many :order_info_brands, class_name: 'OrderInfoBrand', dependent: :delete_all
  has_many :order_infos, through: :order_info_brands
  # ===============================================


  # ===============================================
  # 전시 전용 모델 관계
  has_many :side_menu_items, class_name: 'Store::SideMenuItem', as: :connectable
  # ===============================================


  def official_site_url
    '#'
  end

  def use_pixel?
    pixel_id.present?
  end

  # Company::ApproveRequest
  class ApproveRequest < ::ApproveRequest
    default_scope { where(approvable_type: :Brand) }
  end
end

app/models/haravan/brand.rb
module Haravan
  class Brand < Api::Record
    self.schema = %i[name _items]

    def self.http_auth
      {

      }
    end

    def variants
      @variants ||= _items.group_by(&:variant_id).map { |variant_id, variant_items| Variant.new(id: variant_id, items: variant_items) }
    end

    def total
      @total ||= Vo::Total.new(_items)
    end

    def rowspan
      @rowspan ||= variants.map(&:prices).flatten.count + 1
    end
  end
end

app/controllers/api/v1/brands_controller.rb
module Api
  module V1
    class BrandsController < BaseController
      before_action :authenticate_request!
      before_action :set_brand, only: %i[show update destroy]

      # GET /brands
      # GET /brands.json
      def index
        @brands = decorator_class.decorate_collection(Brand.all)

        render json: @brands
      end

      # GET /brands/1
      # GET /brands/1.json
      def show
        render json: @brand
      end

      # POST /brands
      # POST /brands.json
      def create
        @brand = Brand.new(brand_params)

        if @brand.save
          render json: @brand, status: :created
        else
          render json: @brand.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /brands/1
      # PATCH/PUT /brands/1.json
      def update
        if @brand.update(brand_params)
          render json: @brand, status: :ok
        else
          render json: @brand.errors, status: :unprocessable_entity
        end
      end

      # DELETE /brands/1
      # DELETE /brands/1.json
      def destroy
        @brand.destroy
      end

      protected

      def default_decorator_name
        'Brands::DefaultDecorator'
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_brand
        @brand = decorator_class.decorate(Brand.find(params[:id]))
      end

      # Only allow a list of trusted parameters through.
      def brand_params
        params.fetch(:brand, {})
      end
    end
  end
end

app/controllers/gomisa/brands/base_controller.rb
module Gomisa
  module Brands
    class BaseController < ::Gomisa::BaseController
      before_action :set_brand

      private

      def set_brand
        @brand = Brand.find(params[:brand_id])
      end
    end
  end
end

app/controllers/gomisa/brands/companies_controller.rb
module Gomisa
  module Brands
    class CompaniesController < BaseController
      before_action :set_company, only: %i[show]

      def show
      end

      private

      def set_company
        @company = @brand.company
      end
    end
  end
end

app/controllers/gomisa/brands_controller.rb
module Gomisa
  class BrandsController < BaseController
    before_action :set_brand, only: [:show, :edit, :update, :destroy]
    before_action do
      ActiveStorage::Current.host = request.base_url
    end
    # GET /gomisa/brands
    # GET /gomisa/brands.json
    def index
      @brands = Brand.all
    end

    # GET /gomisa/brands/1
    # GET /gomisa/brands/1.json
    def show
    end

    def create
      @brand = Brand.new(brand_params)

      if @brand.save
        render json: @brand, status: :created
      else
        render json: @brand.errors, status: :unprocessable_entity
      end
    end

    def update
      @brand.attributes = brand_params

      if @brand.save
        render json: @brand, status: :reset_content
      else
        render json: @brand.errors, status: :unprocessable_entity
      end
    end

    def destroy
      # delete will only delete current object record from db but not its associated children records from db.
      # destroy will delete current object record from db and also its associated children record from db.
      begin
        @brand.delete
        render json: {}, status: :no_content
      rescue ActiveRecord::InvalidForeignKey => e
        render json: { error: e.to_s }, status: :failed_dependency
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:company_id, :eng_name, :pixel_id, :logo, name: {})
    end
  end
end

app/controllers/gomisa/companies/brands_controller.rb
module Gomisa
  module Companies
    class BrandsController < BaseController
      before_action :set_brand, only: %i[show]

      def index
        @brands = @company.brands
      end

      def show
      end

      private

      def set_brand
        @brand = @company.brands.find(params[:id])
      end
    end
  end
end

app/controllers/haravan/settlement/brands_controller.rb
module Haravan
  module Settlement
    class BrandsController < ApplicationController
      http_basic_authenticate_with(
          name: Rails.application.credentials.dig(:haravan, :http_basic, :name),
          password: Rails.application.credentials.dig(:haravan, :http_basic, :passwd),
          only: :index
      )
      before_action :brand_http_authenticate, only: :show
      before_action :set_from_time_to_time
      layout 'haravan/settlement'

      def index
        search

        respond_to do |format|
          format.html {}
          format.json { render json: @brands }
        end
      end

      def show
        search

        respond_to do |format|
          format.html {}
          format.json { render json: @brands }
        end
      end

      private

      def brand_http_authenticate
        brand_auth = Haravan::Brand.http_auth || {}
        authenticate_or_request_with_http_basic do |username, password|
          if Rails.application.credentials.dig(:haravan, :http_basic, :name)
            return true if Rails.application.credentials.dig(:haravan, :http_basic, :passwd)
          end
          username == params[:id] && (brand_auth[username].presence || username) == password.to_s
        end
      end

      def search
        set_terms(@from_day..@to_day)

        @orders_count = Haravan::Order.count_by(
            created_at_min: @terms.start_at,
            created_at_max: @terms.end_at
        )

        @service = Haravan::SettlementService.new(@terms, params)
        @brands = @service.call
        @delivered_orders_count = @service.orders.count

        unless params.dig(:id).present?
          message_args = {
              '기간내 전체 주문' => "<b>#{helpers.unit_format(@orders_count, unit: '건')}</b>",
              '기간내 해당 주문' => "<b>#{helpers.unit_format(@service.orders.count, unit: '건')}</b>"
          }

          @subject = message_args.map { |label, value| "<span class='px-2 d-block d-sm-inline-block'>#{label}: #{value}</span>" }.join('<span class="d-none d-sm-inline-block"> | </span>')
        end

        @search_method = params.dig(:search, :method).to_s
        @method_labels = {
            'fulfillment_status' => '배송 완료',
            'financial_status' => '결제 완료',
            '' => '배송 완료'
        }
      end

      def set_from_time_to_time
        @from_day = to_datetime(params[:from], Time.now.in_time_zone('UTC').beginning_of_day)
        @to_day = to_datetime(params[:to], @from_day + 1.day)
      end

      def to_datetime(string, default)
        string.in_time_zone('UTC').to_date rescue default.in_time_zone('UTC').to_date
      end

      def set_terms(time_range = nil)
        time_range = time_range || (Time.now.in_time_zone('UTC').yesterday.beginning_of_day..Time.now.in_time_zone('UTC').yesterday.end_of_day)
        @terms = Haravan::Vo::Terms.new(time_range.first, time_range.last)
      end
    end
  end
end

app/controllers/partner/brands/base_controller.rb
module Partner
  module Brands
    class BaseController < ::Partner::BaseController
      before_action :authenticate_request!
      before_action :set_brands
      before_action :set_brand

      private

      def set_brands
        @brands = current_user.brands.includes(include_tables)
      end

      def set_brand
        @brand = @brands.find(params[:brand_id])
      end

      def include_tables
        [:company, :country]
      end
    end
  end
end

app/controllers/partner/brands/product_item_groups_controller.rb
module Partner
  module Brands
    class ProductItemGroupsController < BaseController
      before_action :set_product_item_group, only: %i[show update destroy]

      # GET /partner/brands/1/product_item_groups
      # GET /partner/brands/1/product_item_groups.json
      def index
        @product_item_groups = @brand.product_item_groups.all
      end

      # GET /partner/brands/1/product_item_groups/1
      # GET /partner/brands/1/product_item_groups/1.json
      def show
      end

      # POST /partner/brands/1/product_item_groups
      # POST /partner/brands/1/product_item_groups.json
      def create
        @product_item_group = ProductItemGroup.new(product_item_group_params.merge(brand: @brand))

        if @product_item_group.save
          render :show, status: :created, location: [:partner, @brand, @product_item_group]
        else
          render json: @product_item_group.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /partner/brands/1/product_item_groups/1
      # PATCH/PUT /partner/brands/1/product_item_groups/1.json
      def update
        if @product_item_group.update(product_item_group_params)
          render :show, status: :ok, location: [:partner, @brand, @product_item_group]
        else
          render json: @product_item_group.errors, status: :unprocessable_entity
        end
      end

      # DELETE /partner/brands/1/product_item_groups/1
      # DELETE /partner/brands/1/product_item_groups/1.json
      def destroy
        @product_item_group.destroy
      end


      private

      # Use callbacks to share common setup or constraints between actions.
      def set_product_item_group
        @product_item_group = @brand.product_item_groups.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def product_item_group_params
        params.require(:product_item_group).permit(:name, items_attributes: [
            *ProductItem.attribute_names,
            :_destroy,
            :cfs,
            :msds,
            :ingredient_table,
            box_images: [],
            images: [],
        ])
      end
    end
  end
end

app/controllers/partner/brands/product_items_controller.rb
module Partner
  module Brands
    class ProductItemsController < BaseController
      before_action :set_product_item, only: %i[show update destroy]

      # GET /partner/brands/1/product_items
      # GET /partner/brands/1/product_items.json
      def index
        @product_items = @brand.items.all
      end

      # GET /partner/brands/1/product_items/1
      # GET /partner/brands/1/product_items/1.json
      def show
      end

      # POST /partner/brands/1/product_items
      # POST /partner/brands/1/product_items.json
      def create
        @product_item = @brand.items.new(product_item_params)

        if @product_item.save
          render :show, status: :created, location: [:partner, @brand, @product_item]
        else
          render json: @product_item.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /partner/brands/1/product_items/1
      # PATCH/PUT /partner/brands/1/product_items/1.json
      def update
        if @product_item.update(product_item_params)
          render :show, status: :ok, location: [:partner, @brand, @product_item]
        else
          render json: @product_item.errors, status: :unprocessable_entity
        end
      end

      # DELETE /partner/brands/1/product_items/1
      # DELETE /partner/brands/1/product_items/1.json
      def destroy
        @product_item.destroy
      end


      private

      # Use callbacks to share common setup or constraints between actions.
      def set_product_item
        @product_item = @brand.items.find(params[:id])
      end

      # Example
      # ===
      #
      # <input name="product_item[array][][name]" value="">
      # {
      #     product_item: {
      #         array: [
      #             { name: '' }
      #         ]
      #     }
      # }
      def product_item_params
        params.require(:product_item).permit(
            :country_id,    # required
            :item_group_id,       # required
            :active,
            :name,                # required
            :serial_number,
            :cost_price,
            :selling_price,

            # === File fields
            :cfs,                 # CFS
            :msds,                # MSDS
            :ingredient_table,    # 전성분표
            box_images: [],       # 단상자 디자인
            images: [],           # 품목 이미지
        )
      end
    end
  end
end

app/controllers/partner/brands_controller.rb
module Partner
  class BrandsController < BaseController
    before_action :authenticate_request!
    before_action :set_brand, only: %i[show edit update destroy]

    # GET /partner/brands
    # GET /partner/brands.json
    def index
      my_brands = @current_user.brands.includes(include_tables).where(query_param)
      @brands = decorator_class.decorate_collection(my_brands)

      render json: @brands
    end

    # GET /partner/brands/1.json
    def show
      render json: @brand
    end

    # POST /partner/brands.json
    def create
      @brand = Brand.new(brand_params)
      # @brand.logo = params[:logo].permit! if params[:logo].present?

      if @brand.save
        render :show, status: :created
      else
        render json: @brand.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /partner/brands/1.json
    def update
      @brand.assign_attributes(brand_params)
      # @brand.logo = params[:logo].permit! if params[:logo].present?

      if @brand.save
        render :show, status: :ok
      else
        render json: @brand.errors, status: :unprocessable_entity
      end
    end

    # DELETE /partner/brands/1.json
    def destroy
      @brand.destroy
      head :no_content
    end

    protected

    def default_decorator_name
      'Brands::DefaultDecorator'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      my_brand = @current_user.brands.find(params[:id])
      @brand = decorator_class.decorate(my_brand)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      country = Country.find(params[:brand][:country_id])
      name = params[:brand][:name]
      params[:brand][:name] = name.merge(country.locale => name['en'])

      params.require(:brand).permit(:company_id, :country_id, :logo, name: {})
    end

    def include_tables
      [:company, :country]
    end

    def query_param
      params.permit(*Brand.attribute_names, id: [])
    end
  end
end

app/helpers/api/v1/brands_helper.rb
module Api::V1::BrandsHelper
end

app/helpers/gomisa/brands_helper.rb
module Gomisa::BrandsHelper
end

app/helpers/partner/brands/product_item_groups_helper.rb
module Partner::Brands::ProductItemGroupsHelper
end

app/helpers/partner/brands/product_items_helper.rb
module Partner::Brands::ProductItemsHelper
end

app/helpers/partner/brands_helper.rb
module Partner::BrandsHelper
end

app/views/haravan/settlement/brands/index.html.erb
<% content_for(:page_title, '해당 Brand 전체') %>

<!--<div id="brandData" data-brands="<%##= @service.brands.to_json %>"></div>-->
<% content_for :search_console do %>
  <form action="<%= haravan_settlement_brands_path(format: :html) %>" onsubmit="return confirm('구간이 넓은 조회는 5 ~ 10 분 가량 소요됩니다.\n새로 고침 하지 말고 기다려주세요.\n계속 진행할까요?')">
    <div class="form-row">
      <div class="col-12 col-sm-6 col-md-4 mb-3">
        <label for="range-from">시작일</label>
        <input name="from" id="range-from" class="form-control form-control-sm datePicker" value="<%= @from_day.strftime('%F') %>">
      </div>

      <div class="col-12 col-sm-6 col-md-4 mb-3">
        <label for="range-to">종료일</label>
        <input name="to" id="range-to" class="form-control form-control-sm datePicker" value="<%= @to_day.strftime('%F') %>">
      </div>

      <div class="col-12 col-md-4 mb-3">
        <label for="search-method">세부조건</label>
        <select name="search[method]" id="search-method" class="form-control form-control-sm">
          <option value="fulfillment_status"  <%= 'selected' if @search_method.presence.nil? || @search_method == 'fulfillment_status' %>><%= @method_labels['fulfillment_status'] %></option>
          <option value="financial_status" <%= 'selected' if @search_method == 'financial_status' %>><%= @method_labels['financial_status'] %></option>
        </select>
      </div>

      <div class="col"></div>

      <div class="col-12 mb-3 text-right">
        <div class="btn-group btn-group-sm float-left" role="group" aria-label="Basic example">
          <a href="<%= haravan_settlement_brands_path(format: :html, from: (@from_day - 1.month).strftime('%F'), to: (@from_day).strftime('%F'), search: { method: params.dig(:search, :method) }) %>"
             onclick="return confirm('월 단위 조회는 3 ~ 10 분 가량 소요됩니다.\n새로 고침 하지 말고 기다려주세요.\n계속 진행할까요?')"
             class="btn btn-outline-secondary rounded-0"><%= (@from_day - 1.month).month %>월</a>
          <a href="<%= haravan_settlement_brands_path(format: :html, from: (Time.now.in_time_zone('UTC').beginning_of_month).strftime('%F'), to: (Time.now.in_time_zone('UTC').beginning_of_month + 1.month).strftime('%F'), search: { method: params.dig(:search, :method) }) %>"
             onclick="return confirm('월 단위 조회는 3 ~ 10 분 가량 소요됩니다.\n새로 고침 하지 말고 기다려주세요.\n계속 진행할까요?')"
             class="btn btn-outline-secondary rounded-0"><%= @from_day.month %>월</a>
          <a href="<%= haravan_settlement_brands_path(format: :html, from: (@from_day + 1.month).strftime('%F'), to: (@from_day + 2.month).strftime('%F'), search: { method: params.dig(:search, :method) }) %>"
             onclick="return confirm('월 단위 조회는 3 ~ 10 분 가량 소요됩니다.\n새로 고침 하지 말고 기다려주세요.\n계속 진행할까요?')"
             class="btn btn-outline-secondary rounded-0"><%= (@from_day + 1.month).month %>월</a>
        </div>

        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
          <button class="btn btn-primary rounded-0">조회</button>
          <a href="<%= haravan_settlement_brands_path(format: :html) %>" class="btn btn-success rounded-0">초기화(Today)</a>
        </div>
      </div>
    </div>
  </form>
<% end %>

<%= render 'sublayout' do %>
  <% @brands.each.with_index do |brand, brand_index| %>
    <!-- brand / total -->
    <tr class="tr-brand tr-brand-<%= brand_index %>" data-brand_index="<%= brand_index %>" data-rowspan="<%= brand.rowspan %>">
      <!-- # -->
      <th class="d-none d-sm-table-cell" rowspan="1" data-column_name="index"><%= brand_index + 1 %></th>

      <!-- 브랜드 -->
      <th class="text-nowrap" rowspan="1" data-toggle="brand_folder" data-column_name="brand_name"><%= brand.name %></th>

      <td class="table-warning" colspan="2" data-column_name="brand_total">총 계</td>

      <!-- 주문건수 -->
      <td class="table-warning text-nowrap text-right" data-toggle="modal" data-target="#order-list-modal"><%= brand.total.orders.count %> 건</td>

      <!-- 합계수량 -->
      <td class="table-warning text-nowrap text-right"><%= unit_format(brand.total.quantity) %></td>

      <!-- 합계금액 -->
      <td class="table-warning text-nowrap text-right"><%= currency_format(brand.total.price, unit: 'VND') %></td>
    </tr>

    <!-- brand / variants -->
    <% brand.variants.each do |variant| %>
      <% variant.prices.each.with_index do |variant_price, pricing_index| %>
        <% variant_item = variant_price.items.first %>

        <tr class="tr-sku tr-brand-<%= brand_index %>" style="display: none;">
          <% if pricing_index.zero? %>
            <!-- 상품명 -->
            <td rowspan="<%= variant.prices.count %>">
              <span><%= variant_item.title %></span>
              <small class="d-block text-muted">[SKU: <b><%= variant_item.sku || '-' %></b> / Variant ID: <b><%= variant.id %></b>]</small>
              <p class="d-block" style="margin: 0">
                <% if variant.prices.count > 1 %>
                  <small class="badge badge-info"># 다중가격</small>
                <% end %>
              </p>
            </td>
          <% end %>

          <!-- 판매가 -->
          <td class="text-right text-nowrap"><%= currency_format(variant_price.price, unit: 'VND') %></td>

          <!-- 주문건수 -->
          <td class="text-right text-nowrap"
              data-toggle="modal" data-target="#order-list-modal"
              data-variant_title="<%= variant_item.title %>"
              data-sku="<%= variant_item.sku %>"
              data-variant_id="<%= variant.id %>"
              data-variant_price="<%= variant_price.price %>"
              data-orders="<%= variant_price.items.to_json %>"><%= variant_price.total.orders.count %> 건</td>

          <!-- 합계수량 -->
          <td class="text-right text-nowrap"><%= unit_format(variant_price.total.quantity) %></td>

          <!-- 합계금액 -->
          <td class="text-right text-nowrap"><%= currency_format(variant_price.total.price, unit: 'VND') %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>

  <style>
    #toggle_brand-all,
    [data-toggle="brand_folder"] {
      cursor: pointer;
      position: relative;
    }

    #toggle_brand-all:hover,
    [data-toggle="brand_folder"]:hover {
      background-color: #ffe186 !important;
    }

    #toggle_brand-all:after,
    [data-toggle="brand_folder"]:after {
      content: '[펼치기]';
      /*position: absolute;*/
      /*top: 0;*/
      /*bottom: 0;*/
      /*right: .5rem;*/
      /*margin: auto 0;*/
      /*height: 1rem;*/
      font-weight: initial;
      margin-left: 10px;
      /*height: 3px;*/
      /*border-left: 3px solid transparent;*/
      /*border-right: 3px solid transparent;*/
      /*border-top: 3px solid;*/
      /*border-bottom: 3px solid transparent;*/
    }

    #toggle_brand-all.spanned:after,
    tr.spanned > [data-toggle="brand_folder"]:after {
      content: '[접기]';
      /*border-bottom: 3px solid;*/
      /*border-top: 3px solid transparent;*/
    }
  </style>
  <script>
    function toggle_brand(trigger, spanned) {
        var root_tr = trigger.closest('.tr-brand');
        var rowspan = root_tr.dataset.rowspan;
        var brand_index = root_tr.dataset.brand_index;

        var rowspan_trs = $(root_tr.querySelectorAll('th[rowspan]'));
        var sku_trs = $('.tr-sku.tr-brand-'+brand_index);

        var toggle_method = spanned === undefined ? root_tr.classList.contains('spanned') : spanned;

        if (toggle_method) {
            rowspan_trs.attr('rowspan', 1);
            sku_trs.hide();
            root_tr.classList.remove('spanned');
        } else {
            rowspan_trs.attr('rowspan', rowspan);
            sku_trs.show();
            root_tr.classList.add('spanned');
        }
    }

    $(function() {
        $('[data-toggle="brand_folder"]').click(function() {
            toggle_brand(this);
        });

        $('#toggle_brand-all').click(function() {
            var spanned = this.classList.contains('spanned');
            $('[data-toggle="brand_folder"]').each(function(i, el) {
                toggle_brand(el, spanned);
            });
            this.classList.toggle('spanned');
        })
    })
  </script>
<% end %>

<%= console if Rails.env == 'development' %>